<?php
/**
 * Created by PhpStorm.
 * User: JS
 * Date: 2017/3/27
 * Time: 11:04
 */

namespace app\modules\datas;


class Module extends \yii\base\Module
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}