<?php
/**
 * Created by PhpStorm.
 * User: JS
 * Date: 2017/3/22
 * Time: 10:53
 */

namespace app\modules\common;


class Module extends \yii\base\Module
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}